### PR TITLE
SCALRCORE-27104 Provider configurations: Allow built-in providers to …

### PR DESCRIPTION
**Pull request by DayS1eeper**
…be registered as custom.[API_BRANCH]

### Changelog
* [ ] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

### CODE REVIEW

**Review by petroprotsakh — APPROVED** [review]
Looks good

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Comment by emocharnik** [comment]
@DayS1eeper, Required builds are failing.

**Pull request merged**
